builds:
  -
    main: cmd/ded/main.go
    binary: ded
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archive:
  name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
