language: go
go: 1.9
install:
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/mattn/goveralls
  - dep ensure
  - gometalinter --install
script:
  - go build
  - go test ./..
  - gometalinter --vender ./...
after_success:
  - goveralls -service=travis-ci
notifications:
  email: false
